name: Deploy to OVH

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    name: 📤 Upload to OVH FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5

        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/
          local-dir: ./
          dangerous-clean-slate: true
          log-level: verbose

